#x_min, y_min, x_max, y_max
boxes: [
    [0, 0, 8, 4],   # defines the world boundary
    [1, 0.5, 3, 1],  # upper-left obstacle
    [3, 0, 5, 1.9],  # upper-center obstacle
    [3, 2.1, 5, 4],  # lower-center obstacle
    [1, 2, 2, 2.5],  # middle-left obstacle
    [5.5, 2, 6.5, 2.5],  # middle-right obstacle
    [6, 0.5, 7, 3],  # upper-right obstacle
    [0.5, 1.5, 1.5, 2],  # vertical obstacle in the middle-left
    [6, 2.5, 7.5, 3],  # diagonal obstacle in the middle-right
    # additional walls can be added as needed
]

epsilon: 0.025